sudo: true
dist: trusty
language: cpp
os: linux

addons:
  apt:
    packages:
      - cmake

before_install:
  - sudo apt-get update -y
  - cd $HOME/build/gf712/ProStruct
  - git submodule update --init
  - source devtools/travis-ci/install_libraries.sh
  - cd $HOME/build/gf712/ProStruct

install:
  - mkdir build
  - cd build
  - cmake -DENABLE_TESTING=ON ..
  - make -j4

# Run tests
script:
  - ./tests/prostruct-unit-tests