sudo: true
dist: trusty
language: cpp
os: linux
# Handle git submodules yourself
git:
  submodules: false

addons:
  apt:
    packages:
      - cmake

before_install:
  - sudo apt-get update -y
  - cd $HOME/build/gf712/ProStruct
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive
  - source devtools/travis-ci/install_libraries.sh
  - cd $HOME/build/gf712/ProStruct

install:
  - mkdir build
  - cd build
  - cmake -DENABLE_TESTING=ON ..
  - make -j4

# Run tests
script:
  - env CTEST_OUTPUT_ON_FAILURE=1 make test