sudo: true
dist: trusty
language: cpp
os: linux

addons:
  apt:
    packages:
      - cmake

before_install:
  - sudo apt-get update -y
  # make sure this is the correct directory
  - cd $HOME/build/gf712/ProStruct
  - source devtools/travis-ci/install_libraries.sh
  - cd $HOME/build/gf712/ProStruct

install:
  - mkdir build
  - cd build
  - cmake ..
  - make -j4

# Run tests
script:
  - env CTEST_OUTPUT_ON_FAILURE=1 make test